name: Deploy – Development (preview)
on:
  push:
    branches: [ dev ]
permissions: { contents: read, pages: write, id-token: write }
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Prepare artifact
        run: |
          mkdir -p out/preview
          cp -R preview/* out/preview/
      - uses: actions/upload-pages-artifact@v3
        with: { path: out }
      - uses: actions/deploy-pages@v4
