name: Deploy – Production
on: { workflow_dispatch: {} }  # manual trigger only (for now)
permissions: { contents: read, pages: write, id-token: write }
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build prod from preview
        run: |
          mkdir -p out
          cp -R preview/* out/
          grep -rl 'noindex, nofollow' out | xargs -r sed -i 's/noindex, nofollow/index, follow/g'
          grep -rl '/preview/' out | xargs -r sed -i 's/\/preview\//\//g'
      - uses: actions/upload-pages-artifact@v3
        with: { path: out }
      - uses: actions/deploy-pages@v4
